AWSTemplateFormatVersion: '2010-09-09'
Description: CloudMart Application Stack

Resources:

  ProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-product-lambda

      Runtime: python3.12
      Handler: index.handler

      Role:
        Fn::ImportValue: ProductLambdaRoleArn

      Timeout: 30

      Code:
        ZipFile: |
          import json

          def handler(event, context):
              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Product Lambda Working"
                  })
              }

  ProductApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: CloudMartProductApi

  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ProductApi
      ParentId: !GetAtt ProductApi.RootResourceId
      PathPart: products

  ProductLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProductLambda
      Principal: apigateway.amazonaws.com

Outputs:

  ProductLambdaArn:
    Description: Product Lambda ARN
    Value: !GetAtt ProductLambda.Arn

  ApiId:
    Description: API Gateway ID
    Value: !Ref ProductApi