AWSTemplateFormatVersion: '2010-09-09'
Description: CloudMart Application Stack

Resources:

  ProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-product-lambda

      Runtime: python3.12
      Handler: index.handler

      Role:
        Fn::ImportValue: ProductLambdaRoleArn

      Timeout: 30

      Code:
        ZipFile: |
          import json

          def handler(event, context):
              return {
                  "statusCode": 200,
                  "body": json.dumps({
                      "message": "Product Lambda Working"
                  })
              }

  ProductApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: CloudMartProductApi

  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ProductApi
      ParentId: !GetAtt ProductApi.RootResourceId
      PathPart: products

  ProductLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProductLambda
      Principal: apigateway.amazonaws.com

  AuthorizerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: cloudmart-authorizer
      Principal: apigateway.amazonaws.com

  ProductAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CloudMartAuthorizer
      RestApiId: !Ref ProductApi
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      AuthorizerResultTtlInSeconds: 300
      AuthorizerUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cloudmart-authorizer/invocations"

  GetProductsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ProductApi
      ResourceId: !Ref ProductsResource
      HttpMethod: GET

      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ProductAuthorizer

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProductLambda.Arn}/invocations"

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetProductsMethod

    Properties:
      RestApiId: !Ref ProductApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ProductApi
      DeploymentId: !Ref ApiDeployment
      StageName: dev

  SchemaInitializerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-schema-initializer

      Runtime: python3.12
      Handler: index.handler

      Role:
        Fn::ImportValue: ProductLambdaRoleArn

      Timeout: 120

      Code:
        ZipFile: |
          import pymysql
          import boto3
          import json

          ssm = boto3.client('ssm')

          def get_parameter(name):
              response = ssm.get_parameter(
                  Name=name,
                  WithDecryption=True
              )
              return response['Parameter']['Value']

          def handler(event, context):

              host = get_parameter('/cloudmart/dev/db/host')
              database = get_parameter('/cloudmart/dev/db/name')
              username = get_parameter('/cloudmart/dev/db/username')
              password = get_parameter('/cloudmart/dev/db/password')

              connection = pymysql.connect(
                  host=host,
                  user=username,
                  password=password,
                  database=database,
                  connect_timeout=10
              )

              cursor = connection.cursor()

              cursor.execute("""
              CREATE TABLE IF NOT EXISTS products (
                  product_id INT AUTO_INCREMENT PRIMARY KEY,
                  product_name VARCHAR(255) NOT NULL,
                  description TEXT,
                  category VARCHAR(100),
                  price DECIMAL(10,2) NOT NULL,
                  stock_count INT NOT NULL DEFAULT 0,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                      ON UPDATE CURRENT_TIMESTAMP,
                  is_active BOOLEAN DEFAULT TRUE
              )
              """)

              cursor.execute("""
              INSERT IGNORE INTO products
              (
                  product_id,
                  product_name,
                  description,
                  category,
                  price,
                  stock_count
              )
              VALUES
              (
                  1,
                  'Laptop',
                  'Dell Inspiron Laptop',
                  'Electronics',
                  65000.00,
                  20
              ),
              (
                  2,
                  'Mouse',
                  'Wireless Mouse',
                  'Electronics',
                  500.00,
                  10
              )
              """)
              ,
              (
                  3,
                  'Mouse',
                  'Wired Mouse',
                  'Electronics',
                  300.00,
                  10
              )
              """)

              connection.commit()

              cursor.close()
              connection.close()

              return {
                  'statusCode': 200,
                  'body': json.dumps('Products table created successfully')
              }
  SchemaInitializerTrigger:
    Type: Custom::SchemaInitializer

    Properties:
      ServiceToken: !GetAtt SchemaInitializerLambda.Arn


Outputs:

  ProductLambdaArn:
    Description: Product Lambda ARN
    Value: !GetAtt ProductLambda.Arn

  ApiId:
    Description: API Gateway ID
    Value: !Ref ProductApi

  ProductsApiUrl:
    Description: Products API URL
    Value: !Sub "https://${ProductApi}.execute-api.${AWS::Region}.amazonaws.com/dev/products"
  
  SchemaInitializerLambdaArn:
    Description: Schema Initializer Lambda ARN
    Value: !GetAtt SchemaInitializerLambda.Arn
  
  