AWSTemplateFormatVersion: '2010-09-09'
Description: CloudMart Application Stack

Resources:

  ProductLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: cloudmart-product-lambda
      Runtime: python3.12
      Handler: index.handler

      Role:
        Fn::ImportValue: ProductLambdaRoleArn

      Timeout: 30

      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: CloudMart-Lambda-SG
        SubnetIds:
          - Fn::ImportValue: CloudMart-Private-Subnet-A-ID
          - Fn::ImportValue: CloudMart-Private-Subnet-B-ID

      Environment:
        Variables:
          DB_HOST: "{{resolve:ssm:/cloudmart/dev/db/host}}"
          DB_USER: "{{resolve:ssm:/cloudmart/dev/db/username}}"
          DB_PASSWORD: "{{resolve:ssm:/cloudmart/dev/db/password}}"
          DB_NAME: "{{resolve:ssm:/cloudmart/dev/db/name}}"

      Code:
        ZipFile: |
          import os
          import json
          import pymysql

          DB_HOST = os.environ['DB_HOST']
          DB_USER = os.environ['DB_USER']
          DB_PASSWORD = os.environ['DB_PASSWORD']
          DB_NAME = os.environ['DB_NAME']

          def get_connection():
              return pymysql.connect(
                  host=DB_HOST,
                  user=DB_USER,
                  password=DB_PASSWORD,
                  database=DB_NAME,
                  connect_timeout=10
              )

          def create_schema(connection):
              with connection.cursor() as cursor:

                  cursor.execute("""
                  CREATE TABLE IF NOT EXISTS products (
                      product_id INT AUTO_INCREMENT PRIMARY KEY,
                      product_name VARCHAR(100) NOT NULL,
                      description TEXT,
                      category VARCHAR(50),
                      price DECIMAL(10,2) NOT NULL,
                      stock_count INT NOT NULL,
                      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                          ON UPDATE CURRENT_TIMESTAMP,
                      is_active BOOLEAN DEFAULT TRUE
                  )
                  """)

                  cursor.execute("""
                  INSERT IGNORE INTO products
                  (product_id, product_name, description, category, price, stock_count)
                  VALUES
                  (1,'Laptop','Dell Inspiron Laptop','Electronics',65000.00,20),
                  (2,'Mouse','Wireless Mouse','Accessories',799.00,50),
                  (3,'Keyboard','Mechanical Keyboard','Accessories',2499.00,30),
                  (4,'Monitor','24 Inch Monitor','Electronics',12999.00,15)
                  """)

              connection.commit()

          def handler(event, context):

              connection = get_connection()

              create_schema(connection)

              with connection.cursor(pymysql.cursors.DictCursor) as cursor:
                  cursor.execute("SELECT * FROM products")
                  products = cursor.fetchall()

              connection.close()

              return {
                  "statusCode": 200,
                  "headers": {
                      "Content-Type": "application/json"
                  },
                  "body": json.dumps(products, default=str)
              }
  ProductApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: CloudMartProductApi

  ProductsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ProductApi
      ParentId: !GetAtt ProductApi.RootResourceId
      PathPart: products

  ProductLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProductLambda
      Principal: apigateway.amazonaws.com

  AuthorizerLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: cloudmart-authorizer
      Principal: apigateway.amazonaws.com

  ProductAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      Name: CloudMartAuthorizer
      RestApiId: !Ref ProductApi
      Type: TOKEN
      IdentitySource: method.request.header.Authorization
      AuthorizerResultTtlInSeconds: 300
      AuthorizerUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:cloudmart-authorizer/invocations"

  GetProductsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ProductApi
      ResourceId: !Ref ProductsResource
      HttpMethod: GET

      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ProductAuthorizer

      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ProductLambda.Arn}/invocations"

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetProductsMethod

    Properties:
      RestApiId: !Ref ProductApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ProductApi
      DeploymentId: !Ref ApiDeployment
      StageName: dev
  

Outputs:

  ProductLambdaArn:
    Description: Product Lambda ARN
    Value: !GetAtt ProductLambda.Arn

  ApiId:
    Description: API Gateway ID
    Value: !Ref ProductApi

  ProductsApiUrl:
    Description: Products API URL
    Value: !Sub "https://${ProductApi}.execute-api.${AWS::Region}.amazonaws.com/dev/products"
  