AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: CloudMart Authorizer Stack

Resources:

  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: cloudmart-authorizer
      Runtime: python3.12
      Handler: index.handler

      CodeUri: ../lambdas/authorizer/

      Role:
        Fn::ImportValue: LambdaAuthorizerRoleArn

      Timeout: 30

Outputs:

  LambdaAuthorizerArn:
    Value: !GetAtt LambdaAuthorizerFunction.Arn
    Export:
<<<<<<< HEAD
      Name: LambdaAuthorizerArn
=======
      Name: LambdaAuthorizerArn
            
>>>>>>> api
