AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: CloudMart Orders Stack

Resources:

  OrderNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: cloudmart-order-notifications

  OrderEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: kundelakomala@gmail.com
      TopicArn: !Ref OrderNotificationsTopic

  OrderEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: cloudmart-order-events

      EventPattern:
        source:
          - cloudmart.orders

        detail-type:
          - OrderPlaced
          - OrderConfirmed
          - OrderFailed

      State: ENABLED

      Targets:
        - Arn: !Ref OrderNotificationsTopic
          Id: OrderNotificationsTarget

  OrderTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref OrderNotificationsTopic

      PolicyDocument:
        Version: '2012-10-17'

        Statement:
          - Sid: AllowEventBridgeToPublish

            Effect: Allow

            Principal:
              Service: events.amazonaws.com

            Action:
              - sns:Publish

            Resource: !Ref OrderNotificationsTopic

  OrderTopicArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /cloudmart/dev/orders/topic-arn
      Type: String
      Value: !Ref OrderNotificationsTopic

Outputs:

  OrderTopicArn:
    Description: Order Notification Topic ARN
    Value: !Ref OrderNotificationsTopic
    Export:
      Name: CloudMart-Order-Topic-Arn