name: CloudMart Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  # ---------------------------
  # NETWORK STACK
  # ---------------------------

  lint-network:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint Network Stack
        run: |
          cfn-lint --non-zero-exit-code error cloudformation/network-stack.yaml

  deploy-network:
    needs: lint-network
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ap-south-1

      - name: Validate Network Stack
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/network-stack.yaml

      - name: Deploy Network Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/network-stack.yaml \
            --stack-name cloudmart-network-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

  # ---------------------------
  # DATA STACK
  # ---------------------------

  lint-data:
    needs: deploy-network
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint Data Stack
        run: |
          cfn-lint --non-zero-exit-code error cloudformation/data-stack.yaml

  deploy-data:
    needs: lint-data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ap-south-1

      - name: Validate Data Stack
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/data-stack.yaml

      - name: Deploy Data Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/data-stack.yaml \
            --stack-name cloudmart-data-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

  # ---------------------------
  # IAM STACK
  # ---------------------------

  lint-iam:
    needs: deploy-data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint IAM Stack
        run: |
          cfn-lint --non-zero-exit-code error cloudformation/iam-stack.yaml

  deploy-iam:
    needs: lint-iam
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ap-south-1

      - name: Validate IAM Stack
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/iam-stack.yaml

      - name: Deploy IAM Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/iam-stack.yaml \
            --stack-name cloudmart-iam-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

  # ---------------------------
  # AUTH STACK
  # ---------------------------

  lint-auth:
    needs: deploy-iam
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint Auth Stack
        run: |
          cfn-lint --non-zero-exit-code error cloudformation/auth-stack.yaml

  deploy-auth:
    needs: lint-auth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ap-south-1

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate Auth Stack
        run: |
          sam validate \
            --template-file cloudformation/auth-stack.yaml

      - name: Build Auth Stack
        run: |
          sam build \
            --template-file cloudformation/auth-stack.yaml

      - name: Deploy Auth Stack
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name cloudmart-auth-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --resolve-s3 \
            --no-fail-on-empty-changeset \
            --region ap-south-1

  # ---------------------------
  # PRODUCT STACK
  # ---------------------------

  lint-product:
    needs: deploy-auth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint Product Stack
        run: |
          cfn-lint --non-zero-exit-code error cloudformation/product-stack.yaml

  deploy-product:
    needs: lint-product
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ap-south-1

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate Product Stack
        run: |
          sam validate \
            --template-file cloudformation/product-stack.yaml

      - name: Build Product Stack
        run: |
          sam build \
            --template-file cloudformation/product-stack.yaml

      - name: Deploy Product Stack
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name cloudmart-product-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --resolve-s3 \
            --no-fail-on-empty-changeset \
            --region ap-south-1

    # ---------------------------
  # ORDER STACK
  # ---------------------------

  lint-order:
    needs: deploy-product
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint Order Stack
        run: |
          cfn-lint --non-zero-exit-code error cloudformation/orders-stack.yaml

  deploy-order:
    needs: lint-order
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ap-south-1

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate Order Stack
        run: |
          sam validate \
            --template-file cloudformation/orders-stack.yaml

      - name: Build Order Stack
        run: |
          sam build \
            --template-file cloudformation/orders-stack.yaml

      - name: Deploy Order Stack
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name cloudmart-orders-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --resolve-s3 \
            --no-fail-on-empty-changeset \
            --region ap-south-1
