name: CloudMart Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-network:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ARN_ROLE}}
          aws-region: ap-south-1

      - name: Verify AWS Connection
        run: aws sts get-caller-identity

      - name: Validate Network Stack
        run: |
          aws cloudformation validate-template \
          --template-body file://cloudformation/network-stack.yaml

      - name: Deploy Network Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/network-stack.yaml \
            --stack-name cloudmart-network-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Check Stack Status
        run: |
          aws cloudformation describe-stacks \
            --stack-name cloudmart-network-stack \
            --query "Stacks[0].StackStatus"

      - name: Validate Data Stack
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/data-stack.yaml

      - name: Deploy Data Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/data-stack.yaml \
            --stack-name cloudmart-data-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Check Stack Status
        run: |
          aws cloudformation describe-stacks \
            --stack-name cloudmart-data-stack