name: Order Stack

on:
  push:
    branches:
      - orders

permissions:
  id-token: write
  contents: read

jobs:

  lint-order:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Lint Order Stack
        run: |
          cfn-lint --non-zero-exit-code error cloudformation/orders-stack.yaml

  deploy-order:
    needs: lint-order
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          aws-region: ap-south-1

      - name: Verify AWS Connection
        run: aws sts get-caller-identity

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Validate Order Stack
        run: |
          sam validate \
            --template-file cloudformation/orders-stack.yaml

      - name: Build Order Stack
        run: |
          sam build \
            --template-file cloudformation/orders-stack.yaml

      - name: Deploy Order Stack
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name cloudmart-orders-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --resolve-s3 \
            --no-fail-on-empty-changeset \
            --region ap-south-1

      - name: Check Order Stack Status
        run: |
          aws cloudformation describe-stacks \
            --stack-name cloudmart-orders-stack

      - name: Show Order Stack Events On Failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name cloudmart-orders-stack